name: Build Example Presentation
on:
  push:
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Compile document
        uses: xu-cheng/latex-action@v2
        with:
          root_file: example.tex

      - name: Upload PDF
        uses: actions/upload-artifact@v2
        with:
          name: Presentation
          path: presentation.pdf
